version: '3.1'
services:
  postgres:
    image: 'postgres:11.1-alpine'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=animal-web
    ports:
      - '5432:5432'
