version: '3.1'
services:
  postgres:
    image: 'postgres:11.1-alpine'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
